filmfanatics2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('', include('reviews.urls', 'reviews')),
    path('', include('users.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

movies/urls.py
from django.urls import path
from .views import movie_list, movie_detail, search_results, home

app_name = 'movies'  # Add this line to set the app_name

urlpatterns = [
    path('', home, name='home'),
    path('movies/', movie_list, name='movie_list'),
    path('movies/<int:movie_id>/', movie_detail, name='movie_detail'),
    path('search/', search_results, name='search_results'),
]

reviews/urls.py
from django.urls import path
from .views import review_list, add_review, edit_review, delete_review

app_name = 'reviews'

urlpatterns = [
    path('add/<int:movie_id>/', add_review, name='add_review'),
    path('movies/<int:movie_id>/reviews/', review_list, name='review_list'),
    path('edit/<int:review_id>/', edit_review, name='edit_review'),
    path('delete/<int:review_id>/', delete_review, name='delete_review'),
]

users/urls.py
from django.urls import path
from .views import register, profile

urlpatterns = [
    # Other URL patterns
    path('register/', register, name='register'),
    path('accounts/profile/', profile, name='profile'),
]

movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_date = models.DateField()
    genre = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

movies/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie
from django.http import HttpResponse
from .utils.api import fetch_movie_data, fetch_movie_data_by_title
from django.conf import settings
import requests
from reviews.models import Review
from reviews.forms import ReviewForm


def movie_list(request):
    # Fetch a list of movies from the API
    movies_data = fetch_movie_data()

    if not movies_data:
        # Handle the case where movie data couldn't be fetched
        return render(request, 'movies/movie_list.html', {'error': 'Movies not found'})

    movies = movies_data.get('results', [])  # Adjust this based on the structure of your API response

    return render(request, 'movies/movie_list.html', {'movies': movies})


def movie_detail(request, movie_id=None, movie_title=None):
    if movie_id:
        movie_data = fetch_movie_data(movie_id)
    elif movie_title:
        # Fetch movie data based on the title
        movie_data = fetch_movie_data_by_title(movie_title)
    else:
        return render(request, 'movies/movie_detail.html', {'error': 'Movie not found'})

    if movie_data:
        # Fetch reviews for the current movie title
        reviews = Review.objects.filter(movie_details=movie_data.get('title', 'N/A'))

        context = {
            'movie_data': movie_data,
            'reviews': reviews,
            'review_form': ReviewForm(),  # Include an instance of the review form for submitting new reviews
        }

        return render(request, 'movies/movie_detail.html', context)
    else:
        return render(request, 'movies/movie_detail.html', {'error': 'Movie not found'})

def home(request):
    # Your view logic here
    return render(request, 'movies/home.html')  # Adjust the template name as needed

def search_results(request):
    query = request.GET.get('query')

    if query:
        
        api_key = settings.API_KEY
        api_url = 'https://api.themoviedb.org/3/search/movie'
        params = {'api_key': api_key, 'query': query}
        
        response = requests.get(api_url, params=params)

        if response.status_code == 200:
            movies_data = response.json().get('results', [])
            context = {'movies_data': movies_data, 'query': query}
            return render(request, 'movies/search_results.html', context)
        else:
            error_message = f'Failed to fetch search results from API: {response.status_code}'
            context = {'error_message': error_message}
            return render(request, 'movies/search_results.html', context)

    else:
        return render(request, 'movies/search_results.html', {'query': query})

movies/templates/movies/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Welcome to the Film Fanatics Home Page!</h2>
    <img class="responsive-img" src="https://i.imgur.com/eelnbzb.png" alt="Film Fanatics">
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% if movie_data %}
            <div class="row">
                <div class="col s12 m6 offset-m3"> <!-- Use offset-m3 to center the content on medium screens -->
                    <div class="card">
                        <div class="card-image">
                            <img src="https://image.tmdb.org/t/p/w500{{ movie_data.poster_path }}" alt="{{ movie_data.title }} Poster">
                            <span class="card-title">{{ movie_data.title }}</span>
                        </div>
                        <div class="card-content">
                            <p>Release Date: {{ movie_data.release_date }}</p>
                            <p>Genre: 
                                {% for genre in movie_data.genres %}
                                    {{ genre.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                            <p>Overview: {{ movie_data.overview }}</p>

                            {% if reviews %}
                                <h3>Reviews</h3>
                                <ul class="collection">
                                    {% for review in reviews %}
                                    <li class="collection-item">
                                        {{ review.user.user.username }} - Rating: {{ review.rating }}/10 - {{ review.comment }}
                                        {% if request.user == review.user.user %}
                                            <a href="{% url 'reviews:edit_review' review.id %}" class="waves-effect waves-light btn">Edit</a>
                                            <a href="{% url 'reviews:delete_review' review.id %}" class="waves-effect waves-light btn red">Delete</a>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                                </ul>
                            {% else %}
                                <p>No reviews available for this movie.</p>
                            {% endif %}

                            <!-- Add other fields as needed -->
                            {% if movie_data.id %}
                                <a href="{% url 'reviews:add_review' movie_data.id %}" class="waves-effect waves-light btn">Add a Review</a>
                            {% else %}
                                <p>Cannot add a review for this movie.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <p>{{ error }}</p>
        {% endif %}
    </div>
{% endblock %}

movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="center">Movies List</h1>
  <ul>
    {% for movie in movies %}
      <li class="center">
        <a  href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}
        <div class="card-image">
          <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie_data.title }} Poster">
          <span class="card-title">{{ movie_data.title }}</span>
      </div>
        </a>
        <!-- Add other movie details as needed -->
      </li>
    {% endfor %}
  </ul>
{% endblock %}

movies/templates/movies/search_results.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="center">Search Results for "{{ query }}"</h2>

    {% if movies_data %}
        <ul class="center">
            {% for movie in movies_data %}
                <li><a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}
                <div class="card-image">
                    <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie_data.title }} Poster">
                    <span class="card-title">{{ movie_data.title }}</span>
                </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No search results found.</p>
    {% endif %}
{% endblock %}